tasks:
  - name: Avvio database e server Node.js
    init: |
      docker-compose up -d
      npm install
      npm run populate-db
    command: |
      npm start

ports:
  - port: 3000
    onOpen: open-browser
  - port: 8080
    onOpen: open-preview
  - port: 5432
    onOpen: ignore
