version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: fotogram_user
      POSTGRES_PASSWORD: fotogram_password
      POSTGRES_DB: fotogram_db
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
  
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  db-data:
